language: python
branches:
  only:
  - master
  - /^\d\.\d+$/
  - /^v\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=py27-scrapy105
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
install:
  - pip install tox
  - pip install -U tox coverage codecov pytest-xdist
script:
  - tox
after_success:
  - codecov
cache:
  directories:
  - $HOME/.cache/pip
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  on:
    tags: true
    condition: $TOXENV == py36 && $TRAVIS_TAG =~ ^v[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$
  password:
    secure: 05NUQdIRHlT+9T85SJXWfg35q3bk7vlpkfHfwisDkbcJnD5+kymRTzbSzhABQxh3bpc0QHRc2bF1PfgCjumaJMarp3K0unsOdptleUwhorizkyvnD8xzxWd+8GFUDBzoCLJqC9TQK05wWrTqbGbZ+stPnatEx7SfJEHbxhKeL7M=
